FROM ros:jazzy



RUN apt update
RUN apt-get install -y -qq \
    python3-pip \
    python3-tk \
    vim git tmux tree sl htop x11-apps

RUN apt-get install -y -qq \
    ros-${ROS_DISTRO}-foxglove-bridge \
    ros-${ROS_DISTRO}-rosbag2-storage-mcap \
    ros-${ROS_DISTRO}-ros-gz \
    ros-${ROS_DISTRO}-ros2-control ros-${ROS_DISTRO}-ros2-controllers ros-${ROS_DISTRO}-gz-ros2-control


# ABSOLUTELY DO NOT use single quotes inside this block
# end any new lines with "\n\" (no quotes)
RUN printf '\n# automatically generated by Dockerfile \n\
    source "/opt/ros/jazzy/setup.bash" --                \n\
    cd laika_ws                                              \n\
    colcon build --symlink-install                        \n\
    source install/local_setup.bash                       \n\
    \n' >> ~/.bashrc

# add mouse to tmux
RUN echo 'set -g mouse on' >> ~/.tmux.conf
