#ifndef laika_pid_controller__laika_pid_controller_HPP_
#define laika_pid_controller__laika_pid_controller_HPP_

#include "controller_interface/controller_interface.hpp"
#include "control_toolbox/pid.hpp"
#include "control_msgs/msg/dynamic_joint_state.hpp"
#include "realtime_tools/realtime_thread_safe_box.hpp"

// auto-generated by generate_parameter_library
#include "laika_pid_controller/laika_pid_controller_parameters.hpp"

namespace laika_pid_controller
{
using CommandType = control_msgs::msg::DynamicJointState;
class LaikaPidController : public controller_interface::ControllerInterface
{
  struct Joint {
    Joint() {};
    // parameters
    std::string name;
    uint8_t id;
    std::shared_ptr<control_toolbox::Pid> velocity_pid;
    std::shared_ptr<control_toolbox::Pid> position_pid;

    double position_state = std::numeric_limits<double>::quiet_NaN();
    double velocity_state = std::numeric_limits<double>::quiet_NaN();
    double effort_state = std::numeric_limits<double>::quiet_NaN();

    double position_reference = std::numeric_limits<double>::quiet_NaN();

    double effort_command = std::numeric_limits<double>::quiet_NaN();
  };
public:
  LaikaPidController();
  controller_interface::CallbackReturn on_init() override;
  controller_interface::InterfaceConfiguration command_interface_configuration() const override;
  controller_interface::InterfaceConfiguration state_interface_configuration() const override;
  controller_interface::CallbackReturn on_configure(const rclcpp_lifecycle::State & previous_state) override;
  controller_interface::CallbackReturn on_activate(const rclcpp_lifecycle::State & previous_state) override;
  controller_interface::return_type update(const rclcpp::Time & time, const rclcpp::Duration & period) override;
  controller_interface::CallbackReturn on_deactivate(const rclcpp_lifecycle::State & previous_state) override;

protected:
  std::shared_ptr<ParamListener> param_listener;
  Params params;

  // joints
  std::vector<Joint> joints;

  // listener
  realtime_tools::RealtimeThreadSafeBox<CommandType> rt_buffer;
  CommandType reference_msg;
  rclcpp::Subscription<CommandType>::SharedPtr joints_cmd_sub;

  // helper functions
  void get_joint_states();
  void get_joint_references();
};

}  // namespace laika_pid_controller

#endif  // laika_pid_controller__laika_pid_controller_HPP_
