#ifndef LAIKA_CARTESIAN_IMPEDANCE_CONTROLLER_HPP_
#define LAIKA_CARTESIAN_IMPEDANCE_CONTROLLER_HPP_

#include <memory>
#include <string>
#include <vector>

#include "controller_interface/controller_interface.hpp"
#include "rclcpp_lifecycle/state.hpp"
#include "realtime_tools/realtime_buffer.hpp"
#include <std_msgs/msg/float64_multi_array.hpp>
// Auto-generated by generate_parameter_library
#include <laika_cartesian_impedance_controller/laika_cartesian_impedance_controller_parameters.hpp>

namespace laika_cartesian_impedance_controller
{
using CommandType = std_msgs::msg::Float64MultiArray;

struct JointData {
  std::string name;
  int id;
  double position_state = std::numeric_limits<double>::quiet_NaN();
  double velocity_state = std::numeric_limits<double>::quiet_NaN();
  double effort_state = std::numeric_limits<double>::quiet_NaN();
  double effort_command = 0.0;
};

class LaikaCartesianImpedanceController : public controller_interface::ControllerInterface
{
public:
  LaikaCartesianImpedanceController();

  controller_interface::CallbackReturn on_init() override;
  controller_interface::CallbackReturn on_configure(const rclcpp_lifecycle::State & previous_state) override;
  controller_interface::CallbackReturn on_activate(const rclcpp_lifecycle::State & previous_state) override;
  controller_interface::CallbackReturn on_deactivate(const rclcpp_lifecycle::State & previous_state) override;
  
  controller_interface::InterfaceConfiguration command_interface_configuration() const override;
  controller_interface::InterfaceConfiguration state_interface_configuration() const override;
  
  controller_interface::return_type update(const rclcpp::Time & time, const rclcpp::Duration & period) override;

private:
  void get_joint_states();
  void get_cartesian_reference();

  std::shared_ptr<laika_cartesian_impedance_controller::ParamListener> param_listener_;
  laika_cartesian_impedance_controller::Params params_;

  std::vector<JointData> joints_;
  
  rclcpp::Subscription<CommandType>::SharedPtr cartesian_cmd_sub_;
  realtime_tools::RealtimeBuffer<CommandType> rt_buffer_;
  CommandType reference_msg_;

  double x_ref_ = 0.0;
  double y_ref_ = 0.0;
  double dx_ref_ = 0.0;
  double dy_ref_ = 0.0;
  double fx_ff_ = 0.0;
  double fy_ff_ = 0.0;

  // Placeholder lengths pending URDF integration
  //static constexpr double LINK_LENGTH_HIP = 0.35;
  //static constexpr double LINK_LENGTH_KNEE = 0.41;
  //static constexpr double GEAR_RATIO = 14.0;

  static constexpr double LINK_LENGTH_UPPER = 0.35;
  static constexpr double LINK_LENGTH_LOWER = 0.41;
  static constexpr double KNEE_OFFSET = 0.04573;
  static constexpr double GEAR_RATIO = 14.0;
};

}  // namespace laika_cartesian_impedance_controller

#endif  // LAIKA_CARTESIAN_IMPEDANCE_CONTROLLER_HPP_
